### ISSUE TITLE
在浏览器输入 URL 回车之后发生了什么（超详细版） - 4Ark

### ISSUE THREAD

**Issue by gd4Ark** [gd4Ark/gd4Ark.github.io#35]
https://4ark.me/post/b6c7c0a2.html 

 在浏览器输入 URL 回车之后发生了什么（超详细版）

**Comment by dadaewqq** [comment]
红芯浏览器还要列出来么。。

**Comment by wsgzao** [comment]
感谢分享，我可以申请转载吗

**Comment by gd4Ark** [comment]
> @wsgzao
> 感谢分享，我可以申请转载吗

当然可以

**Comment by bboy-xp** [comment]
👍🏻👍🏻👍🏻

**Comment by stardustman** [comment]
expire

**Comment by stardustman** [comment]
楼主的评论是怎样弄的? 可以告知吗? 谢谢

**Comment by gd4Ark** [comment]
@stardustman gitalk

**Comment by jerryc127** [comment]
转载。。已注明来源。。你的文章很棒。

**Comment by stardustman** [comment]
expire 过期拼错了

**Comment by stardustman** [comment]
楼主的 gitalk 是怎样配置的呢？谢谢。

**Comment by gd4Ark** [comment]
> @stardustman
> 楼主的 gitalk 是怎样配置的呢？谢谢。

可以看一下我这个博客的仓库：[链接](https://github.com/gd4Ark/gd4Ark.github.io)

**Comment by aitaozi** [comment]
您好，我可以转载这篇文章到公众号吗，会声明原创作者和链接，谢谢

**Comment by gd4Ark** [comment]
> @aitaozi
> 您好，我可以转载这篇文章到公众号吗，会声明原创作者和链接，谢谢

当然可以
