### ISSUE TITLE
2020 年度总结 - 4Ark

### ISSUE THREAD

**Issue by gd4Ark** [gd4Ark/gd4Ark.github.io#62]
https://4ark.me/post/b0a39503.html 

 2020 年度总结

**Comment by levy9527** [comment]
学英语可以试试这本书： 把你的英语用起来。我看这本书学习的

**Comment by warmsirius** [comment]
很棒，你的blog，我一直都在追~

**Comment by gd4Ark** [comment]
> @warmsirius
> 很棒，你的blog，我一直都在追~

一起加油

**Comment by gd4Ark** [comment]
> @levy9527
> 学英语可以试试这本书： 把你的英语用起来。我看这本书学习的

好，现在马上搜😬
