### ISSUE TITLE
1从 Composition API 源码分析 getCurrentInstance() 为何返回 null - 4Ark

### ISSUE THREAD

**Issue by gd4Ark** [gd4Ark/gd4Ark.github.io#63]
https://4ark.me/post/87ba8d8b.html 

 1从 Composition API 源码分析 getCurrentInstance() 为何返回 null

**Comment by jerryc127** [comment]
你好，我的域名更換了，麻煩你更新下
原名為 JerryC

現為
名字： MYW
地址： https://immyw.com/
頭像： https://immyw.com/img/avatar.png
簡介： 今日事,今日畢
