### ISSUE TITLE
理解 JavaScript 中的作用域 - 4Ark' Blog

### ISSUE THREAD

**Issue by gd4Ark** [gd4Ark/gd4Ark.github.io#9]
https://4ark.me/post/b845344a.html 

 理解 JavaScript 中的作用域

**Comment by getr00t** [comment]
我感觉这里用变量提示的称呼更合适吧？

**Comment by gd4Ark** [comment]
> @TDcloud
> 我感觉这里用变量提示的称呼更合适吧？

这是业界公认的专业术语
